services:
  backend:
    image: backend-app 
    env_file:
      - ./apps/backend/.env 
    
    command: python3 -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 -m app.main
    
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./apps/backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYDEVD_DISABLE_FILE_VALIDATION=1
      - NVIDIA_VISIBLE_DEVICES=all