from .base import Base

from uuid import UUID
from typing import TYPE_CHECKING

from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import ForeignKey, text, String, Text

if TYPE_CHECKING:
    from .project import Project

class QuestionAndAnswer(Base):
    __tablename__ = "question_and_answer"

    id: Mapped[UUID] = mapped_column(primary_key=True, index=True, server_default=text("gen_random_uuid()"))

    question: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="The question posed by the user"
    )
    answer: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="The answer generated by the system"
    )

    total_processing_time_ms: Mapped[int] = mapped_column(
        nullable=False,
        comment="Total time taken to generate the answer in milliseconds"
    )

    total_token_count: Mapped[int] = mapped_column(
        nullable=False,
        comment="Total number of tokens used in generating the answer"
    )

    project_id: Mapped[UUID] = mapped_column(
        ForeignKey("project.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="The project this Q&A pair is associated with"
    )
    project: Mapped["Project"] = mapped_column(
        relationship("Project", back_populates="question_and_answers")
    )


