from .base import Base

from uuid import UUID
from typing import TYPE_CHECKING
from datetime import datetime

from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import ForeignKey, text, Text
from sqlalchemy import Enum as SQLEnum

from app.pydantic.status import ProcessingStatus


if TYPE_CHECKING:
    from .project import Project

class QuestionAndAnswer(Base):
    __tablename__: str = "question_and_answer"

    id: Mapped[UUID] = mapped_column(primary_key=True, index=True, server_default=text("gen_random_uuid()"))

    # core fields
    question: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="The question posed by the user"
    )
    answer: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="The answer generated by the system"
    )
    
    # time relevant fields 
    start_time: Mapped[datetime] = mapped_column(nullable=False, comment="Time when the Q&A processing started")
    end_time: Mapped[datetime] = mapped_column(nullable=True, comment=" Time when the Q&A processing ended")
    total_processing_time_ms: Mapped[int] = mapped_column(
        nullable=True,
        comment="Total time taken to generate the answer in milliseconds"
    )

    status: Mapped[ProcessingStatus] = mapped_column(
        SQLEnum(ProcessingStatus),
        nullable=False,
        comment="Current status of the Q&A processing"
    )

    # LLM relevant fields
    total_output_token_count: Mapped[int] = mapped_column(
        nullable=True,
        comment="Total number of tokens used in generating the answer"
    )

    # foreign keys and relationships
    project_id: Mapped[UUID] = mapped_column(
        ForeignKey("project.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="The project this Q&A pair is associated with"
    )
    project: Mapped["Project"] = relationship(
        "Project", back_populates="questions_and_answers"
    )
    


