from datetime import datetime
from uuid import UUID, uuid4
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
import logging

from app.models import QuestionAndAnswer 
from app.pydantic import ProcessingStatus

logger = logging.getLogger(__name__)


class QuestionAndAnswerService:

    def __init__(self, db: AsyncSession):
        self.db = db


    async def init_q_and_a_record(self, project_id: str, query: str, start_time: datetime) -> QuestionAndAnswer:
        """
        Initialize a Question & Answer record in the database.

        TODO: Consider seperating this Q&A logic into seperate service and having query service FULLY focus on LlamaIndex querying logic 

        Args:
            project_id (str): The ID of the Project being queried.
            query (str): The query string.
            start_time (datetime): The time when the query processing started.
        """

        q_and_a_pk = uuid4()

        q_and_a = QuestionAndAnswer(
            id=q_and_a_pk,
            project_id=project_id,
            question=query,
            answer="",
            start_time=start_time,
            status=ProcessingStatus.IN_PROGRESS
        )
        self.db.add(q_and_a)

        await self.db.flush()
        return q_and_a

    
    async def update_q_and_a_record(
            self, 
            id: UUID,
            output_tokens: int, 
            end_time: datetime,
            status: ProcessingStatus,
            answer: str,
            total_processing_time_ms: int
    ):
        """
        Update a Question & Answer record in the database with processing results.

        Args:
            id (UUID): The ID of the Q&A record to update.
            output_tokens (int): The number of output tokens generated by the LLM.
            end_time (datetime): The time when the query processing ended.
            status (ProcessingStatus): The final status of the processing.
            answer (str): The generated answer from the LLM.
            total_processing_time_ms (int): Total processing time in milliseconds.
        """

        # Query for the record by ID
        stmt = select(QuestionAndAnswer).where(QuestionAndAnswer.id == id)
        result = await self.db.execute(stmt)
        q_and_a = result.scalar_one_or_none()

        if q_and_a is None:
            raise ValueError(f"Question & Answer record with ID {id} not found")

        # Update the record fields
        q_and_a.end_time = end_time
        q_and_a.status = status
        q_and_a.answer = answer
        q_and_a.total_processing_time_ms = total_processing_time_ms
        q_and_a.total_output_token_count = output_tokens

        self.db.add(q_and_a)
        await self.db.commit()

        logger.debug(f"Successfully updated QuestionAndAnswer={id} with ProcessingStatus={status}")